<?php

/**
 * This file is encoded in UTF-8, please never change it othrwise this class won't work properly
 * -----
 * Ce fichier est encodé en UTF-8, veuillez ne jamais le changer sinon cette classe ne fonctionnera pas correctement
 */

class QCountry {

    const
        Numeric = 0,
        Alpha2 = 2,
        Alpha3 = 1,

        IsoAF = 'AF', IsoZA = 'ZA', IsoAX = 'AX', IsoAL = 'AL', IsoDZ = 'DZ',
        IsoDE = 'DE', IsoAD = 'AD', IsoAO = 'AO', IsoAI = 'AI', IsoAQ = 'AQ',
        IsoAG = 'AG', IsoSA = 'SA', IsoAR = 'AR', IsoAM = 'AM', IsoAW = 'AW',
        IsoAU = 'AU', IsoAT = 'AT', IsoAZ = 'AZ', IsoBS = 'BS', IsoBH = 'BH',
        IsoBD = 'BD', IsoBB = 'BB', IsoBY = 'BY', IsoBE = 'BE', IsoBZ = 'BZ',
        IsoBJ = 'BJ', IsoBM = 'BM', IsoBT = 'BT', IsoBO = 'BO', IsoBQ = 'BQ',
        IsoBA = 'BA', IsoBW = 'BW', IsoBV = 'BV', IsoBR = 'BR', IsoBN = 'BN',
        IsoBG = 'BG', IsoBF = 'BF', IsoBI = 'BI', IsoKY = 'KY', IsoKH = 'KH',
        IsoCM = 'CM', IsoCA = 'CA', IsoCV = 'CV', IsoCF = 'CF', IsoCL = 'CL',
        IsoCN = 'CN', IsoCX = 'CX', IsoCY = 'CY', IsoCC = 'CC', IsoCO = 'CO',
        IsoKM = 'KM', IsoCG = 'CG', IsoCD = 'CD', IsoCK = 'CK', IsoKR = 'KR',
        IsoKP = 'KP', IsoCR = 'CR', IsoCI = 'CI', IsoHR = 'HR', IsoCU = 'CU',
        IsoCW = 'CW', IsoDK = 'DK', IsoDJ = 'DJ', IsoDO = 'DO', IsoDM = 'DM',
        IsoEG = 'EG', IsoSV = 'SV', IsoAE = 'AE', IsoEC = 'EC', IsoER = 'ER',
        IsoES = 'ES', IsoEE = 'EE', IsoUS = 'US', IsoET = 'ET', IsoFK = 'FK',
        IsoFO = 'FO', IsoFJ = 'FJ', IsoFI = 'FI', IsoFR = 'FR', IsoGA = 'GA',
        IsoGM = 'GM', IsoGE = 'GE', IsoGS = 'GS', IsoGH = 'GH', IsoGI = 'GI',
        IsoGR = 'GR', IsoGD = 'GD', IsoGL = 'GL', IsoGP = 'GP', IsoGU = 'GU',
        IsoGT = 'GT', IsoGG = 'GG', IsoGN = 'GN', IsoGW = 'GW', IsoGQ = 'GQ',
        IsoGY = 'GY', IsoGF = 'GF', IsoHT = 'HT', IsoHM = 'HM', IsoHN = 'HN',
        IsoHK = 'HK', IsoHU = 'HU', IsoIM = 'IM', IsoUM = 'UM', IsoVG = 'VG',
        IsoVI = 'VI', IsoIN = 'IN', IsoID = 'ID', IsoIR = 'IR', IsoIQ = 'IQ',
        IsoIE = 'IE', IsoIS = 'IS', IsoIL = 'IL', IsoIT = 'IT', IsoJM = 'JM',
        IsoJP = 'JP', IsoJE = 'JE', IsoJO = 'JO', IsoKZ = 'KZ', IsoKE = 'KE',
        IsoKG = 'KG', IsoKI = 'KI', IsoKW = 'KW', IsoLA = 'LA', IsoLS = 'LS',
        IsoLV = 'LV', IsoLB = 'LB', IsoLR = 'LR', IsoLY = 'LY', IsoLI = 'LI',
        IsoLT = 'LT', IsoLU = 'LU', IsoMO = 'MO', IsoMK = 'MK', IsoMG = 'MG',
        IsoMY = 'MY', IsoMW = 'MW', IsoMV = 'MV', IsoML = 'ML', IsoMT = 'MT',
        IsoMP = 'MP', IsoMA = 'MA', IsoMH = 'MH', IsoMQ = 'MQ', IsoMU = 'MU',
        IsoMR = 'MR', IsoYT = 'YT', IsoMX = 'MX', IsoFM = 'FM', IsoMD = 'MD',
        IsoMC = 'MC', IsoMN = 'MN', IsoME = 'ME', IsoMS = 'MS', IsoMZ = 'MZ',
        IsoMM = 'MM', IsoNA = 'NA', IsoNR = 'NR', IsoNP = 'NP', IsoNI = 'NI',
        IsoNE = 'NE', IsoNG = 'NG', IsoNU = 'NU', IsoNF = 'NF', IsoNO = 'NO',
        IsoNC = 'NC', IsoNZ = 'NZ', IsoIO = 'IO', IsoOM = 'OM', IsoUG = 'UG',
        IsoUZ = 'UZ', IsoPK = 'PK', IsoPW = 'PW', IsoPS = 'PS', IsoPA = 'PA',
        IsoPG = 'PG', IsoPY = 'PY', IsoNL = 'NL', IsoPE = 'PE', IsoPH = 'PH',
        IsoPN = 'PN', IsoPL = 'PL', IsoPF = 'PF', IsoPR = 'PR', IsoPT = 'PT',
        IsoQA = 'QA', IsoRE = 'RE', IsoRO = 'RO', IsoGB = 'GB', IsoRU = 'RU',
        IsoRW = 'RW', IsoEH = 'EH', IsoBL = 'BL', IsoKN = 'KN', IsoSM = 'SM',
        IsoMF = 'MF', IsoSX = 'SX', IsoPM = 'PM', IsoVA = 'VA', IsoVC = 'VC',
        IsoSH = 'SH', IsoLC = 'LC', IsoSB = 'SB', IsoWS = 'WS', IsoAS = 'AS',
        IsoST = 'ST', IsoSN = 'SN', IsoRS = 'RS', IsoSC = 'SC', IsoSL = 'SL',
        IsoSG = 'SG', IsoSK = 'SK', IsoSI = 'SI', IsoSO = 'SO', IsoSD = 'SD',
        IsoSS = 'SS', IsoLK = 'LK', IsoSE = 'SE', IsoCH = 'CH', IsoSR = 'SR',
        IsoSJ = 'SJ', IsoSZ = 'SZ', IsoSY = 'SY', IsoTJ = 'TJ', IsoTW = 'TW',
        IsoTZ = 'TZ', IsoTD = 'TD', IsoCZ = 'CZ', IsoTF = 'TF', IsoTH = 'TH',
        IsoTL = 'TL', IsoTG = 'TG', IsoTK = 'TK', IsoTO = 'TO', IsoTT = 'TT',
        IsoTN = 'TN', IsoTM = 'TM', IsoTC = 'TC', IsoTR = 'TR', IsoTV = 'TV',
        IsoUA = 'UA', IsoUY = 'UY', IsoVU = 'VU', IsoVE = 'VE', IsoVN = 'VN',
        IsoWF = 'WF', IsoYE = 'YE', IsoZM = 'ZM', IsoZW = 'ZW', IsoXX = 'XX';

    private static $_codes = array(
        array('004', 'AFG', 'AF'),
        array('710', 'ZAF', 'ZA'),
        array('248', 'ALA', 'AX'),
        array('008', 'ALB', 'AL'),
        array('012', 'DZA', 'DZ'),
        array('276', 'DEU', 'DE'),
        array('020', 'AND', 'AD'),
        array('024', 'AGO', 'AO'),
        array('660', 'AIA', 'AI'),
        array('010', 'ATA', 'AQ'),
        array('028', 'ATG', 'AG'),
        array('682', 'SAU', 'SA'),
        array('032', 'ARG', 'AR'),
        array('051', 'ARM', 'AM'),
        array('533', 'ABW', 'AW'),
        array('036', 'AUS', 'AU'),
        array('040', 'AUT', 'AT'),
        array('031', 'AZE', 'AZ'),
        array('044', 'BHS', 'BS'),
        array('048', 'BHR', 'BH'),
        array('050', 'BGD', 'BD'),
        array('052', 'BRB', 'BB'),
        array('112', 'BLR', 'BY'),
        array('056', 'BEL', 'BE'),
        array('084', 'BLZ', 'BZ'),
        array('204', 'BEN', 'BJ'),
        array('060', 'BMU', 'BM'),
        array('064', 'BTN', 'BT'),
        array('068', 'BOL', 'BO'),
        array('535', 'BES', 'BQ'),
        array('070', 'BIH', 'BA'),
        array('072', 'BWA', 'BW'),
        array('074', 'BVT', 'BV'),
        array('076', 'BRA', 'BR'),
        array('096', 'BRN', 'BN'),
        array('100', 'BGR', 'BG'),
        array('854', 'BFA', 'BF'),
        array('108', 'BDI', 'BI'),
        array('136', 'CYM', 'KY'),
        array('116', 'KHM', 'KH'),
        array('120', 'CMR', 'CM'),
        array('124', 'CAN', 'CA'),
        array('132', 'CPV', 'CV'),
        array('140', 'CAF', 'CF'),
        array('152', 'CHL', 'CL'),
        array('156', 'CHN', 'CN'),
        array('162', 'CXR', 'CX'),
        array('196', 'CYP', 'CY'),
        array('166', 'CCK', 'CC'),
        array('170', 'COL', 'CO'),
        array('174', 'COM', 'KM'),
        array('178', 'COG', 'CG'),
        array('180', 'COD', 'CD'),
        array('184', 'COK', 'CK'),
        array('410', 'KOR', 'KR'),
        array('408', 'PRK', 'KP'),
        array('188', 'CRI', 'CR'),
        array('384', 'CIV', 'CI'),
        array('191', 'HRV', 'HR'),
        array('192', 'CUB', 'CU'),
        array('531', 'CUW', 'CW'),
        array('208', 'DNK', 'DK'),
        array('262', 'DJI', 'DJ'),
        array('214', 'DOM', 'DO'),
        array('212', 'DMA', 'DM'),
        array('818', 'EGY', 'EG'),
        array('222', 'SLV', 'SV'),
        array('784', 'ARE', 'AE'),
        array('218', 'ECU', 'EC'),
        array('232', 'ERI', 'ER'),
        array('724', 'ESP', 'ES'),
        array('233', 'EST', 'EE'),
        array('840', 'USA', 'US'),
        array('231', 'ETH', 'ET'),
        array('238', 'FLK', 'FK'),
        array('234', 'FRO', 'FO'),
        array('242', 'FJI', 'FJ'),
        array('246', 'FIN', 'FI'),
        array('250', 'FRA', 'FR'),
        array('266', 'GAB', 'GA'),
        array('270', 'GMB', 'GM'),
        array('268', 'GEO', 'GE'),
        array('239', 'SGS', 'GS'),
        array('288', 'GHA', 'GH'),
        array('292', 'GIB', 'GI'),
        array('300', 'GRC', 'GR'),
        array('308', 'GRD', 'GD'),
        array('304', 'GRL', 'GL'),
        array('312', 'GLP', 'GP'),
        array('316', 'GUM', 'GU'),
        array('320', 'GTM', 'GT'),
        array('831', 'GGY', 'GG'),
        array('324', 'GIN', 'GN'),
        array('624', 'GNB', 'GW'),
        array('226', 'GNQ', 'GQ'),
        array('328', 'GUY', 'GY'),
        array('254', 'GUF', 'GF'),
        array('332', 'HTI', 'HT'),
        array('334', 'HMD', 'HM'),
        array('340', 'HND', 'HN'),
        array('344', 'HKG', 'HK'),
        array('348', 'HUN', 'HU'),
        array('833', 'IMN', 'IM'),
        array('581', 'UMI', 'UM'),
        array('092', 'VGB', 'VG'),
        array('850', 'VIR', 'VI'),
        array('356', 'IND', 'IN'),
        array('360', 'IDN', 'ID'),
        array('364', 'IRN', 'IR'),
        array('368', 'IRQ', 'IQ'),
        array('372', 'IRL', 'IE'),
        array('352', 'ISL', 'IS'),
        array('376', 'ISR', 'IL'),
        array('380', 'ITA', 'IT'),
        array('388', 'JAM', 'JM'),
        array('392', 'JPN', 'JP'),
        array('832', 'JEY', 'JE'),
        array('400', 'JOR', 'JO'),
        array('398', 'KAZ', 'KZ'),
        array('404', 'KEN', 'KE'),
        array('417', 'KGZ', 'KG'),
        array('296', 'KIR', 'KI'),
        array('414', 'KWT', 'KW'),
        array('418', 'LAO', 'LA'),
        array('426', 'LSO', 'LS'),
        array('428', 'LVA', 'LV'),
        array('422', 'LBN', 'LB'),
        array('430', 'LBR', 'LR'),
        array('434', 'LBY', 'LY'),
        array('438', 'LIE', 'LI'),
        array('440', 'LTU', 'LT'),
        array('442', 'LUX', 'LU'),
        array('446', 'MAC', 'MO'),
        array('807', 'MKD', 'MK'),
        array('450', 'MDG', 'MG'),
        array('458', 'MYS', 'MY'),
        array('454', 'MWI', 'MW'),
        array('462', 'MDV', 'MV'),
        array('466', 'MLI', 'ML'),
        array('470', 'MLT', 'MT'),
        array('580', 'MNP', 'MP'),
        array('504', 'MAR', 'MA'),
        array('584', 'MHL', 'MH'),
        array('474', 'MTQ', 'MQ'),
        array('480', 'MUS', 'MU'),
        array('478', 'MRT', 'MR'),
        array('175', 'MYT', 'YT'),
        array('484', 'MEX', 'MX'),
        array('583', 'FSM', 'FM'),
        array('498', 'MDA', 'MD'),
        array('492', 'MCO', 'MC'),
        array('496', 'MNG', 'MN'),
        array('499', 'MNE', 'ME'),
        array('500', 'MSR', 'MS'),
        array('508', 'MOZ', 'MZ'),
        array('104', 'MMR', 'MM'),
        array('516', 'NAM', 'NA'),
        array('520', 'NRU', 'NR'),
        array('524', 'NPL', 'NP'),
        array('558', 'NIC', 'NI'),
        array('562', 'NER', 'NE'),
        array('566', 'NGA', 'NG'),
        array('570', 'NIU', 'NU'),
        array('574', 'NFK', 'NF'),
        array('578', 'NOR', 'NO'),
        array('540', 'NCL', 'NC'),
        array('554', 'NZL', 'NZ'),
        array('086', 'IOT', 'IO'),
        array('512', 'OMN', 'OM'),
        array('800', 'UGA', 'UG'),
        array('860', 'UZB', 'UZ'),
        array('586', 'PAK', 'PK'),
        array('585', 'PLW', 'PW'),
        array('275', 'PSE', 'PS'),
        array('591', 'PAN', 'PA'),
        array('598', 'PNG', 'PG'),
        array('600', 'PRY', 'PY'),
        array('528', 'NLD', 'NL'),
        array('604', 'PER', 'PE'),
        array('608', 'PHL', 'PH'),
        array('612', 'PCN', 'PN'),
        array('616', 'POL', 'PL'),
        array('258', 'PYF', 'PF'),
        array('630', 'PRI', 'PR'),
        array('620', 'PRT', 'PT'),
        array('634', 'QAT', 'QA'),
        array('638', 'REU', 'RE'),
        array('642', 'ROU', 'RO'),
        array('826', 'GBR', 'GB'),
        array('643', 'RUS', 'RU'),
        array('646', 'RWA', 'RW'),
        array('732', 'ESH', 'EH'),
        array('652', 'BLM', 'BL'),
        array('659', 'KNA', 'KN'),
        array('674', 'SMR', 'SM'),
        array('663', 'MAF', 'MF'),
        array('534', 'SXM', 'SX'),
        array('666', 'SPM', 'PM'),
        array('336', 'VAT', 'VA'),
        array('670', 'VCT', 'VC'),
        array('654', 'SHN', 'SH'),
        array('662', 'LCA', 'LC'),
        array('090', 'SLB', 'SB'),
        array('882', 'WSM', 'WS'),
        array('016', 'ASM', 'AS'),
        array('678', 'STP', 'ST'),
        array('686', 'SEN', 'SN'),
        array('688', 'SRB', 'RS'),
        array('690', 'SYC', 'SC'),
        array('694', 'SLE', 'SL'),
        array('702', 'SGP', 'SG'),
        array('703', 'SVK', 'SK'),
        array('705', 'SVN', 'SI'),
        array('706', 'SOM', 'SO'),
        array('729', 'SDN', 'SD'),
        array('728', 'SSD', 'SS'),
        array('144', 'LKA', 'LK'),
        array('752', 'SWE', 'SE'),
        array('756', 'CHE', 'CH'),
        array('740', 'SUR', 'SR'),
        array('744', 'SJM', 'SJ'),
        array('748', 'SWZ', 'SZ'),
        array('760', 'SYR', 'SY'),
        array('762', 'TJK', 'TJ'),
        array('158', 'TWN', 'TW'),
        array('834', 'TZA', 'TZ'),
        array('148', 'TCD', 'TD'),
        array('203', 'CZE', 'CZ'),
        array('260', 'ATF', 'TF'),
        array('764', 'THA', 'TH'),
        array('626', 'TLS', 'TL'),
        array('768', 'TGO', 'TG'),
        array('772', 'TKL', 'TK'),
        array('776', 'TON', 'TO'),
        array('780', 'TTO', 'TT'),
        array('788', 'TUN', 'TN'),
        array('795', 'TKM', 'TM'),
        array('796', 'TCA', 'TC'),
        array('792', 'TUR', 'TR'),
        array('798', 'TUV', 'TV'),
        array('804', 'UKR', 'UA'),
        array('858', 'URY', 'UY'),
        array('548', 'VUT', 'VU'),
        array('862', 'VEN', 'VE'),
        array('704', 'VNM', 'VN'),
        array('876', 'WLF', 'WF'),
        array('887', 'YEM', 'YE'),
        array('894', 'ZMB', 'ZM'),
        array('716', 'ZWE', 'ZW')
    ),
    $_countries = array(
        array('AFGHANISTAN', 'DA AFGHANESTAN ISLAMI JOMHOURIYET', 'JOMHURI YE ESLAMI YE AFGANESTAN', 'REPUBLIQUE ISLAMIQUE D AFGHANISTAN'),
        array('AFRIQUE DU SUD', 'REPUBLIC OF SOUTH AFRICA', 'REPUBLIEK VAN SUID AFRIKA', 'IRIPHABLIKI YASEMZANTSI AFRIKA', 'IRIPHABLIKI YASENINGIZIMU AFRIKA', 'IRIPHABLIKI YESEWULA AFRIKA', 'REPUBLIQUE D AFRIQUE DU SUD'),
        array('ILES ALAND', 'ALAND ILES', 'LANDSKAPET ALAND', 'AHVENANMAAN MAAKUNTA', 'ETAT LIBRE ASSOCIE D ALAND'),
        array('ALBANIE', 'SHQIPE', 'REPUBLIKA E SHQIPERISE', 'REPUBLIQUE D ALBANIE'),
        array('ALGERIE', 'REPUBLIQUE ALGERIENNE DEMOCRATIQUE ET POPULAIRE'),
        array('ALLEMAGNE', 'DEUTSCHLAND', 'GERMANY'),
        array('ANDORRE', 'PRINCIPAT D ANDORRA', 'PRINCIPAUTE D ANDORRE'),
        array('ANGOLA', 'REPUBLICA DE ANGOLA'),
        array('ANGUILLA'),
        array('ANTARCTIQUE', 'TRAITE SUR L ANTARCTIQUE', 'THE ANTARCTIC TREATY', 'TRATADO ANTARCTICO'),
        array('ANTIGUA ET BARBUDA', 'ANTIGUA AND BARBADUA'),
        array('ARABIE SAOUDITE', 'MAMLAKAH AL ARABIYAHAS SU UDIYAH'),
        array('ARGENTINE', 'ARGENTINA'),
        array('ARMENIE', 'HAYASTAN'),
        array('ARUBA'),
        array('AUSTRALIE', 'AUSTRALIA'),
        array('AUTRICHE', 'OSTERREICH'),
        array('AZERBAIDJAN', 'AZRBAYCAN RESPUBLIKASI'),
        array('BAHAMAS', 'COMMONWEALTH OF THE BAHAMAS'),
        array('BAHREIN', 'MAMLAKAT AL BAHRAYN'),
        array('BANGLADESH', 'GONOPROJATONTRI BANGLADESH'),
        array('BARBADE', 'BARBADOS'),
        array('BIELORUSSIE', 'BELARUS', 'BELARUSY'),
        array('BELGIQUE', 'ROYAUME DE BELGIQUE', 'KONINKRIJK', 'BELGIE', 'KONIGREICH', 'BELGIEN', 'BELGIUM'),
        array('BELIZE'),
        array('BENIN', 'ORILE EDE OLOMINIRA ILE BENIN'),
        array('BERMUDES', 'BERMUDA'),
        array('BHOUTAN', 'DRUK YUL'),
        array('BOLIVIE', 'BOLIVIE ETAT PLURINATIONAL DE', 'ESTADO PLURINACIONAL DE BOLIVIA', 'REPUBLICA DE BOLIVIA', 'BULIBIYA MAMA LLAQTA', 'WULIWYA SUYU', 'TETA VOLIVIA'),
        array('PAYS BAS CARIBEENS', 'BONAIRE SAINT EUSTACHE ET SABA', 'BONAIRE SINT EUSTATIUS EN SABA'),
        array('BOSNIE HERZEGOVINE', 'REPUBLIKA BOSNA I HERCEGOVINA'),
        array('BOTSWANA', 'REPUBLIC OF BOTSWANA', 'LEFATSHE LA BOTSWANA'),
        array('ILE BOUVET', 'BOUVET ILE', 'BOUVETOYA'),
        array('BRESIL', 'REPUBLICA FEDERATIVA DO BRASIL'),
        array('BRUNEI', 'BRUNEI DARUSSALAM', 'NEGARA BRUNEI DARUSSALAM', 'STATE OF BRUNEI DARUSSALAM'),
        array('BULGARIE', 'REPUBLIKA BALGARIA'),
        array('BURKINA FASO'),
        array('BURUNDI', 'REPUBLIQUE DU BURUNDI', 'REPUBLIKA Y UBURUNDI'),
        array('ILES CAIMANS', 'CAIMANES ILES', 'CAYMAN ISLANDS'),
        array('CAMBODGE', 'PREAH REACHEANACHAKR KAMPUCHEA'),
        array('CAMEROUN', 'CAMEROON'),
        array('CANADA'),
        array('CAP VERT', 'CABO VERDE'),
        array('REPUBLIQUE CENTRAFRICAINE', 'CENTRAFRICAINE REPUBLIQUE', 'KODOROSESE TI BEAFRIKA'),
        array('CHILI', 'CHILE'),
        array('CHINE', 'ZHONGHUA RENMIN GONGHEGUO'),
        array('ILE CHRISTMAS', 'CHRISTMAS ILE', 'CHRISTMAS ISLANDS'),
        array('CHYPRE', 'KYPROS', 'KIBRIS', 'KYPRIAKI DIMOKRATIA', 'KIBRIS CUMHURIYETI'),
        array('ILES COCOS', 'COCOS ILES', 'TERRITORY OF COCOS ISLAND'),
        array('COLOMBIE', 'COLOMBIA'),
        array('COMORES', 'UNION DES COMORES', 'JUZUR AL QUMUR', 'UDZIMA WA KOMORI'),
        array('REPUBLIQUE DU CONGO', 'CONGO', 'REPUBILIKA YA KONGO', 'REPUBLIKI YA KONGO', 'CONGO BRAZZAVILLE'),
        array('REPUBLIQUE DEMOCRATIQUE DU CONGO', 'CONGO LA REPUBLIQUE DEMOCRATIQUE DU', 'REPUBILIKA YA KONGO DEMOKRATIKI', 'JAMHURI YA KIDEMOKRASIA YA KONGO', 'REPUBLIKI YA KONGO DEMOKRATIKI', 'DITUNGA DIA KONGU WA MUNGALAATA', 'CONGO KINSHASA EX ZAIRE'),
        array('ILES COOK', 'COOK ILES', 'COOK ISLANDS'),
        array('COREE DU SUD', 'COREE REPUBLIQUE DE', 'DAEHAN MIN GUK'),
        array('COREE DU NORD', 'COREE REPUBLIQUE POPULAIRE DEMOCRATIQUE DE', 'CHOSON MINJUJUUI INMIN KONGHWAGUK'),
        array('COSTA RICA', 'REPUBLICA DE COSTA RICA'),
        array('COTE D IVOIRE'),
        array('CROATIE', 'REPUBLIKA HRVATSKA'),
        array('CUBA', 'REPUBLICA DE CUBA'),
        array('CURACAO', 'KORSOU'),
        array('DANEMARK', 'KONGERIGET DANMARK'),
        array('DJIBOUTI', 'REBLIQUE DE DJIBOUTI', 'JUMHURIYYAT JIBUTI', 'GABUUTIH UMMUUNO', 'JAMAHUURIYADA JABUUTI'),
        array('REPUBLIQUE DOMINICAINE', 'DOMINICAINE REPUBLIQUE', 'REPUBLICA DOMINICANA'),
        array('DOMINIQUE', 'COMMONWEALTH OF DOMINICA'),
        array('EGYPTE', 'GUMHURIYYAT MISR AL ARABIYYAH', 'REPUBLIQUE ARABE D EGYPTE'),
        array('SALVADOR', 'EL SALVADOR', 'REPUBLICA DE EL SALVADOR'),
        array('EMIRATS ARABES UNIS', 'AL IMARAT AL ARABIYYAT AL MUTTAHIDA'),
        array('EQUATEUR', 'REPUBLICA DEL ECUADOR'),
        array('ERYTHREE', 'HAGERE ERTRA', 'DAWLAT IRITRIYA', 'STATE OF ERITREA'),
        array('ESPAGNE', 'ESPANA', 'SPAIN'),
        array('ESTONIE', 'EESTI'),
        array('ETATS UNIS', 'UNITED STATES OF AMERICA', 'USA', 'ETATS UNIS D AMERIQUE'),
        array('ETHIOPIE', 'YEITYOPYA FEDERALAWI DIMOKRASIYAWI RIPEBLIK'),
        array('MALOUINES', 'FALKLAND ILES MALVINAS', 'FALKLAND ISLANDS'),
        array('ILES FEROE', 'FEROE ILES', 'FOROYAR', 'FEROERNE'),
        array('FIDJI', 'REPUBLIC OF FIJI', 'MATANITU KO VITI', 'FIJI DVIP QAMOOH GANARAJYA'),
        array('FINLANDE', 'SUOMEN TASAVALTA'),
        array('FRANCE', 'REPUBLIQUE FRANCAISE'),
        array('GABON', 'REPUBLIQUE GABONAISE'),
        array('GAMBIE', 'REPUBLIC OF GAMBIA'),
        array('GEORGIE', 'SAKARTVELO'),
        array('GEORGIE DU SUD ET LES ILES SANDWICH DU SUD'),
        array('GHANA', 'REPUBLIC OF GHANA'),
        array('GIBRALTAR'),
        array('GRECE', 'ELLINIKI DIMOKRATIA'),
        array('GRENADE', 'COMMONWEALTH OF GRENADA'),
        array('GROENLAND', 'KALAALLIT NUNAAT', 'GRONLAND'),
        array('GUADELOUPE'),
        array('GUAM', 'GUAHAN'),
        array('GUATEMALA', 'REPUBLICA DE GUATEMALA'),
        array('GUERNESEY', 'GUERNSEY'),
        array('GUINEE', 'REPUBLIQUE DE GUINEE'),
        array('GUINEE BISSAU', 'REPUBLICA DA GUINE BISSAU'),
        array('GUINEE EQUATORIALE', 'REPUBLICA DE GUIENA ECUATORIAL', 'REPUBLIQUE DE GUINEE EQUATORIALE', 'REPUBLICA DA GUINE EQUATORIAL'),
        array('GUYANA', 'CO OPERATIVE REPUBLIC OF GUYANA', 'REPUBLIQUE COOPERATIVE DU GUYANA'),
        array('GUYANE', 'GUYANE FRANCAISE'),
        array('HAITI', 'REPIBLIK D AYITI', 'REPUBLIQUE D HAITI'),
        array('ILES HEARD ET MACDONALD', 'HEARD ET MACDONALD ILES', 'HEARD ISLAND AND MCDONALD ISLANDS'),
        array('HONDURAS', 'REPUBLICA DE HONDURAS'),
        array('HONG KONG', 'HEUNGGONG', 'HIONG KONG', 'HIONG KANG', 'XIANGGANG', 'HONG KONG SPECIAL ADMINISTRATIVE REGION OF THE PEOPLE S REPUBLIC OF CHINA', 'REGION ADMINISTRATIVE SPECIALE DE HONG KONG DE LA REPUBLIQUE POPULAIRE DE CHINE'),
        array('HONGRIE', 'MAGYAR'),
        array('ILE DE MAN', 'ISLE OF MAN'),
        array('ILES MINEURES ELOIGNEES DES ETATS UNIS', 'UNITED STATES MINOR OUTLYING ISLANDS'),
        array('ILES VIERGES BRITANNIQUES', 'BRITISH VIRGIN ISLANDS'),
        array('ILES VIERGES DES ETATS UNIS', 'US VIRGIN ISLANDS'),
        array('INDE', 'REPUBLIC OF INDIA'),
        array('INDONESIE', 'REPUBLIK INDONESIA'),
        array('IRAN', 'IRAN REPUBLIQUE ISLAMIQUE D ', 'JOMHURI YE ESLAMI YE IRAN'),
        array('IRAK', 'IRAQ', 'AL IRAQ'),
        array('IRLANDE', 'EIRE', 'IRELAND'),
        array('ISLANDE', 'ISLAND'),
        array('ISRAEL', 'MEDINAT YISRA EL', 'DAWLAT ISRA IL'),
        array('ITALIE', 'ITALIA'),
        array('JAMAIQUE', 'JAMAICA'),
        array('JAPON', 'NIHON KOKU'),
        array('JERSEY', 'BAILIWICK OF JERSEY', 'BAILLIAGE DE JERSEY'),
        array('JORDANIE', 'AL MAMLAKAH AL URDUNIYAH AL HASHIMIYAH'),
        array('KAZAKHSTAN', 'QAZAQSTAN RESPUBLIKASI'),
        array('KENYA', 'JAMHURI YA KENYA', 'REPUBLIC OF KENYA'),
        array('KIRGHIZISTAN', 'KIRGIZ RESPUBLIKASI', 'KYRGYZSKAYA RESPUBLIKA'),
        array('KIRIBATI'),
        array('KOWEIT', 'DAWLAT AL KUWAYT'),
        array('LAOS', 'LAO REPUBLIQUE DEMOCRATIQUE POPULAIRE', 'SATHALANALAT PASSATHIPATAI PASSASSON LAO'),
        array('LESOTHO', 'MUSO OA LESOTHO', 'KINGDOM OF LESOTHO'),
        array('LETTONIE', 'LATVIJAS'),
        array('LIBAN', 'REPUBLIQUE DU LIBAN'),
        array('LIBERIA LIBERIA', 'REPUBLIC OF LIBERIA'),
        array('LIBYE', 'DAWLAT LIBIYYA', 'LIBYA'),
        array('LIECHTENSTEIN', 'FURSTENTUM LIECHTENSTEIN'),
        array('LITUANIE', 'LIETUVOS RESPUBLIKA', 'LIETUVA'),
        array('LUXEMBOURG', 'GROUSSHERZOGTUM LETZEBUERG', 'GRAND DUCHE DE LUXEMBOURG', 'GROSSHERZOGTUM LUXEMBURG'),
        array('MACAO', 'REGIAO ADMINISTRATIVA ESPECIAL DE MACAU DA REPUBLICA POPULAR DA CHINA'),
        array('MACEDOINE', 'MACEDOINE L EX REPUBLIQUE YOUGOSLAVE DE'),
        array('MADAGASCAR', 'REPUBLIQUE DE MADAGASCAR', 'REPOBLIKAN I MADAGASIKARA'),
        array('MALAISIE', 'MALAYSIA'),
        array('MALAWI', 'REPUBLIC OF MALAWI', 'DZIKO LA MALAWI'),
        array('MALDIVES', 'DIVEHI RAJJEY GE JUMHURIYYA'),
        array('MALI', 'REPUBLIQUE DU MALI'),
        array('MALTE', 'REPUBBLIKA TA MALTA', 'REPUBLIC OF MALTA'),
        array('ILES MARIANNES DU NORD', 'MARIANNES DU NORD ILES', 'COMMONWEALTH OF THE NORTHERN MARIANA ISLANDS'),
        array('MAROC', 'AL MAMLAKATU L MAGHRIBIYA', 'TAGLDIT N LMEGRIB'),
        array('ILES MARSHALL', 'MARSHALL ILES', 'AOLEPAN AOROKIN M AJEL', 'REPUBLIC OF THE MARSHALL ISLANDS'),
        array('MARTINIQUE'),
        array('MAURICE'),
        array('MAURITANIE', 'REPUBLIQUE ISLAMIQUE DE MAURITANIE'),
        array('MAYOTTE'),
        array('MEXIQUE', 'ESTADOS UNIDOS MEXICANOS'),
        array('MICRONESIE', 'MICRONESIE ETATS FEDERES DE', 'MICRONESIA'),
        array('MOLDAVIE', 'MOLDOVA', 'REPUBLICA MOLDOVA'),
        array('MONACO'),
        array('MONGOLIE', 'MONGOL ULS'),
        array('MONTENEGRO'),
        array('MONTSERRAT'),
        array('MOZAMBIQUE', 'REPUBLICA DE MOCAMBIQUE'),
        array('BIRMANIE', 'MYANMAR', 'UNION OF MYANMAR'),
        array('NAMIBIE', 'NAMIBIA'),
        array('NAURU', 'RIPUBLIK NAOERO', 'REPUBLIC OF NAURU'),
        array('NEPAL'),
        array('NICARAGUA', 'REPUBLICA DE NICARAGUA'),
        array('NIGER'),
        array('NIGERIA'),
        array('NIUE'),
        array('ILE NORFOLK', 'NORFOLK ILE', 'NORFOLK ISLAND'),
        array('NORVEGE', 'KONGERIKET NORGE', 'NOREG'),
        array('NOUVELLE CALEDONIE'),
        array('NOUVELLE ZELANDE', 'NEW ZELAND'),
        array('TERRITOIRE BRITANNIQUE DE L OCEAN INDIEN', 'OCEAN INDIEN TERRITOIRE BRITANNIQUE DE L '),
        array('OMAN', 'SALTANAT UMAN'),
        array('OUGANDA', 'REPUBLIC OF UGANDA', 'JAMHURI YA UGANDA'),
        array('OUZBEKISTAN', 'O ZBEKISTON RESPUBLIKASI'),
        array('PAKISTAN', 'ISLAMI JAMHURIA PAKISTAN'),
        array('PALAOS', 'REPUBLIC OF PALAU', 'BELUU ER A BELAU'),
        array('PALESTINE', 'ETAT DE PALESTINE', 'DAWLAT FILASTIN'),
        array('PANAMA', 'REPUBLICA DE PANAMA'),
        array('PAPOUASIE NOUVELLE GUINEE', 'L ETAT INDEPENDANT DE PAPOUASIE NOUVELLE GUINEE', 'THE INDEPENDENT STATE OF PAPUA NEW GUINEA', 'INDEPENDEN STET BILONG PAPUA NIUGINI'),
        array('PARAGUAY', 'REPUBLICA DEL PARAGUAY', 'TETA PARAGUAYPE '),
        array('PAYS BAS', 'NEDERLAND'),
        array('PEROU', 'PERU'),
        array('PHILIPPINES', 'REPUBLIKA NG PILIPINAS'),
        array('ILES PITCAIRN', 'PITCAIRN'),
        array('POLOGNE', 'POLAND', 'POLSKA'),
        array('POLYNESIE FRANCAISE', 'PORINETIA FARANI'),
        array('PORTO RICO', 'ESTADO LIBRE ASOCIADO DE PUERTO RICO', 'COMMONWEALTH OF PUERTO RICO'),
        array('PORTUGAL'),
        array('QATAR', 'DAWLAT QATAR'),
        array('LA REUNION', 'REUNION'),
        array('ROUMANIE', 'ROMANIA'),
        array('ROYAUME UNI', 'UNITED KINGDOM', 'GRANDE BRETAGNE', 'GREAT BRITAIN'),
        array('RUSSIE', 'RUSSIE FEDERATION DE', 'ROSSIISKAAA FEDERATSIYA'),
        array('RWANDA', 'REPUBULIKA Y U RWANDA', 'REPUBLIQUE RWANDAISE'),
        array('REPUBLIQUE ARABE SAHRAOUIE DEMOCRATIQUE', 'SAHARA OCCIDENTAL'),
        array('SAINT BARTHELEMY'),
        array('SAINT CHRISTOPHE ET NIEVES', 'SAINT KITTS ET NEVIS'),
        array('SAINT MARIN', 'SAN MARINO'),
        array('SAINT MARTIN', 'SAINT MARTIN PARTIE FRANCAISE '),
        array('SINT MAARTEN', 'SAINT MARTIN PARTIE NEERLANDAISE '),
        array('SAINT PIERRE ET MIQUELON'),
        array('SAINT SIEGE ETAT DE LA CITE DU VATICAN', 'STATO DELLA CITTA DEL VATICANO'),
        array('SAINT VINCENT ET LES GRENADINES', 'SAINT VINCENT AND THE GRENADINES'),
        array('SAINTE HELENE ASCENSION ET TRISTAN DA CUNHA', 'SAINT HELENA', 'SAINT HELENE'),
        array('SAINTE LUCIE', 'COMMONWEALTH OF SAINT LUCIA'),
        array('SALOMON', 'SALOMON ILES', 'SALOMONS ISLANDS'),
        array('SAMOA', 'MALO SA OLOTO TUTO ATASI O SAMOA', 'INDEPENDENT STATE OF SAMOA'),
        array('SAMOA AMERICAINES', 'SAMOA'),
        array('SAO TOME ET PRINCIPE', 'REPUBLICA DEMOCRATICA DE SAO TOME E PRINCIPE'),
        array('SENEGAL', 'REPUBLIQUE DU SENEGAL'),
        array('SERBIE', 'REPUBLIKA SRBIJA'),
        array('SEYCHELLES', 'REPIBLIK SESEL', 'REPUBLIC OF SEYCHELLES', 'REPUBLIQUE DES SEYCHELLES'),
        array('SIERRA LEONE'),
        array('SINGAPOUR', 'REPUBLIC OF SINGAPORE', 'REPUBLIK SINGAPURA', 'CINGKAPPURA KUDIYARACU', 'XINJIAPO GONGHEGUO '),
        array('SLOVAQUIE', 'SLOVENSKA REPUBLIKA'),
        array('SLOVENIE', 'REPUBLIKA SLOVENIJA'),
        array('SOMALIE', 'LA REPUBLIQUE FEDERALE DE SOMALIE', 'JAMHUURIYADDA FEDERAALKA SOOMAALIYA', 'THE FEDERAL REPUBLIC OF SOMALIA'),
        array('SOUDAN', 'JUMHURIYAT AL SUDAN'),
        array('SOUDAN DU SUD', 'REPUBLIC OF SOUTH SUDAN'),
        array('SRI LANKA', 'PRAJATANTRIKA SAMAJAVADI JANARAJAYA', 'ILANKAI SANANAYAKA SOSOLISA KUDIYARASU'),
        array('SUEDE', 'SVERIGE'),
        array('SUISSE', 'SCHWEIZERISCHE EIDGENOSSENSCHAFT', 'CONFEDERATION SUISSE', 'CONFEDERAZIONE SVIZZERA', 'CONFEDERAZIUN SVIZRA', 'CONFEDERATION HELVETIQUE'),
        array('SURINAME', 'REPUBLIEK SURINAME'),
        array('SVALBARD ET ILE JAN MAYEN', 'SVALBARD OG JAN MAYEN'),
        array('SWAZILAND', 'UMBUSO WE SWATINI', 'KINGDOM OF SWAZILAND'),
        array('SYRIE', 'SYRIENNE REPUBLIQUE ARABE', 'AL JUMHURIYYAH AL ARABIYYAH AS SURIYYAH'),
        array('TADJIKISTAN', 'JUMHURII TOJIKISTON', 'RESPUBLIKA TADSHIKISTAN'),
        array('TAIWAN', 'TAIWAN PROVINCE DE CHINE', 'REPUBLIQUE DE CHINE TAIWAN', 'FORMOSE'),
        array('TANZANIE', 'TANZANIE REPUBLIQUE UNIE DE', 'UNITED REPUBLIC OF TANZANIA', 'JAMHURI YA MUUNGANO WA TANZANIA'),
        array('TCHAD', 'JUMHURIYYAT TSHAD', 'REPUBLIQUE DU TCHAD'),
        array('REPUBLIQUE TCHEQUE', 'TCHEQUE REPUBLIQUE', 'CESKA REPUBLIKA'),
        array('TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES', 'TERRES AUSTRALES FRANCAISES'),
        array('THAILANDE', 'RATCHA ANACHAK THAI'),
        array('TIMOR ORIENTAL', 'TIMOR LESTE', 'REPUBLIKA DEMOKRATIKA TIMOR LOROSA E', 'REPUBLICA DEMOCRATICA DE TIMOR LESTE'),
        array('TOGO', 'REPUBLIQUE TOGOLAISE'),
        array('TOKELAU'),
        array('TONGA', 'PULE ANGA FAKATU I O TONGA', 'KINGDOM OF TONGA'),
        array('TRINITE ET TOBAGO', 'REPUBLIC OF TRINIDAD AND TOBAGO'),
        array('TUNISIE', 'AL JUMHURIYYA AT TUNISIYYA'),
        array('TURKMENISTAN', 'TURKMENISTAN RESPUBLIKASY', 'RESPUBLIKA TURKMENISTAN'),
        array('ILES TURQUES ET CAIQUES', 'TURKS ET CAIQUES ILES', 'TURKS AND CAICOS'),
        array('TURQUIE', 'TURKIYE CUMHURIYETI'),
        array('TUVALU', 'STATE OF TUVALU'),
        array('UKRAINE', 'UKRAINA'),
        array('URUGUAY', 'REPUBLICA ORIENTAL DEL URUGUAY'),
        array('VANUATU', 'RIPABLIK BLONG VANUATU', 'REPUBLIC OF VANUATU', 'REPUBLIQUE DE VANUATU'),
        array('VENEZUELA', 'VENEZUELA REPUBLIQUE BOLIVARIENNE DU', 'REPUBLICA BOLIVARIANA DE VENEZUELA'),
        array('VIET NAM', 'CONG HOA XA HOI CHU NGHIA VIET NAM', 'LA REPUBLIQUE SOCIALISTE DU VIET NAM'),
        array('WALLIS ET FUTUNA'),
        array('YEMEN'),
        array('ZAMBIE', 'REPUBLIC OF ZAMBIA'),
        array('ZIMBABWE', 'REPUBLIC OF ZIMBABWE')
    );

    public static function fromName($name, $isoType = self::Alpha2){
        if($isoType < self::Numeric || $isoType > self::Alpha2){
            throw new QCountryIsoTypeException('Iso type "' . $isoType . '" is not valid');
        }
        $name = self::_simplify($name);
        foreach(self::$_countries as $k => $countries){
            if(in_array($name, $countries)){
                return self::$_codes[$k][$isoType];
            }
        }
        throw new QCountryException('Country "' . $name . '" is not referenced');
    }

    public static function toFrench($name){
        $name = self::_simplify($name);
        foreach(self::$_countries as $countries){
            if(in_array($name, $countries)){
                return $countries[0];
            }
        }
    }

    public static function fromIsoCode($isoCode, $onlyFrench = true){
        if(strlen($isoCode) == 2){
            $col = self::Alpha2;
        } else if(preg_match('/[\d]{3}/', $isoCode)) {
            $col = self::Numeric;
        } else if(strlen($isoCode) == 3){
            $col = self::Alpha3;
        } else {
            throw new QCountryIsoCodeException('Iso code "' . $isoCode . '" is not valid');
        }
        foreach(self::$_codes as $k => $codes){
            if($codes[$col] == $isoCode){
                return $onlyFrench ? self::$_countries[$k][0] : self::$_countries[$k];
            }
        }
        throw new QCountryException('Iso code "' . $isoCode . '" is not referenced');
    }

    private static function _simplify($utf){
        $ie = mb_internal_encoding();
        $re = mb_regex_encoding();
        mb_regex_encoding('UTF-8');
        mb_internal_encoding('UTF-8');

        $from = array('-', '\'', ',', '`', '̀', 'ʿ', '’', 'ʾ', '‘', '̧', '(', ')', 'Å', 'ä', 'å', 'ǎ', 'ā', 'ă', 'â', 'á', 'à', 'ã', 'ç', 'Ç', 'É', 'Ë', 'È', 'æ', 'è', 'ẹ', 'ë', 'é', 'ê', 'ệ', 'ḥ', 'Ï', 'Í', 'Î', 'ĩ', 'ī', 'î', 'ì', 'ï', 'í', 'Κ', 'ļ', 'ñ', 'Ô', 'Ö', 'ộ', 'ó', 'ö', 'ô', 'ø', 'ō', 'ò', 'ο', 'π', 'ρ' /*r*/, 'ß' /*ss*/, 'ς' /*s*/, 'ṣ', 'ŭ', 'ủ', 'ū', 'ü', 'ú', 'ύ' /*y*/, 'ý');
        $to =   array(' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'A', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'c', 'C', 'E', 'E', 'E', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'h', 'I', 'I', 'I', 'i', 'i', 'i', 'i', 'i', 'i', 'K', 'l', 'n', 'O', 'O', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'p', 'r' /* */, 'ss' /* */, 's' /* */, 's', 'u', 'u', 'u', 'u', 'u', 'y' /* */, 'y');
        $ascii = preg_replace('/\s+/', ' ', str_replace($from, $to, $utf));

        mb_internal_encoding($ie);
        mb_regex_encoding($re);

        $ascii = strtoupper($ascii);
        return $ascii;
    }
}

class QCountryException extends Exception {}
class QCountryIsoTypeException extends QCountryException{}
class QCountryIsoCodeException extends QCountryException{}

?>